version: "3.7"
services:
  registry:
    container_name: registry
    image: registry:latest
    restart: always
    ports:
      - ${APP_PORT}:5000
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
      REGISTRY_STORAGE_DELETE_ENABLED: true
    volumes:
      - ${APP_DATA_DIR}/data:/data
    networks:
      - tipi_main_network
