version: "3.7"
services:
  registry:
    container_name: registry
    image: registry:2
    restart: always
    ports:
      - ${APP_PORT}:5000
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
      REGISTRY_STORAGE_DELETE_ENABLED: true
    volumes:
      - ${APP_DATA_DIR}/mnt/registry:/var/lib/registry
    networks:
      - tipi_main_network
